title: Luke Hoffmann's Personal Portfolio
email: 
description: >-
  A website that holds Luke Hoffmann's personal projects portfolio.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://luke-hoffmann.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
# If you’re not using a theme, remove this line. Otherwise put something like:
# theme: minima

collections:
  college-posts:
    output: true
    permalink: /college-posts/:title/
