title: Luke Hoffmann - Portfolio

description: >-
  Luke Hoffmann's online portfolio of programming projects.
url: "https://lukehoffmann.com" # the base hostname & protocol for your site, e.g. http://example.com


collections:
  college:
    output: true
    permalink: /college/:title/
  projects_p5:
    output: true
    permalink: /projects/p5js/:title/
